### ISSUE TITLE
Angular 4.4.6

### ISSUE THREAD

**Issue by susonwaiba** [Alberthaff/ngx-papaparse#9]
```
ERROR in Error: Metadata version mismatch for module D:/admin/node_modules/ngx-papaparse/ngx-papaparse.d.ts, found version 4, expected 3, resolving symbol AppModule in D:/admin/src/app/app.module.ts, resolving symbol AppModule in D:/admin/src/app/app.module.ts
    at Error (native)
    at syntaxError (D:\admin\node_modules\@angular\compiler\bundles\compiler.umd.js:1729:34)
    at simplifyInContext (D:\admin\node_modules\@angular\compiler\bundles\compiler.umd.js:24979:23)
    at StaticReflector.simplify (D:\admin\node_modules\@angular\compiler\bundles\compiler.umd.js:24991:13)
    at StaticReflector.annotations (D:\admin\node_modules\@angular\compiler\bundles\compiler.umd.js:24418:41)
    at _getNgModuleMetadata (D:\admin\node_modules\@angular\compiler-cli\src\ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (D:\admin\node_modules\@angular\compiler-cli\src\ngtools_impl.js:109:26)
    at Object.listLazyRoutesOfModule (D:\admin\node_modules\@angular\compiler-cli\src\ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (D:\admin\node_modules\@angular\compiler-cli\src\ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (D:\admin\node_modules\@ngtools\webpack\src\plugin.js:212:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (D:\admin\node_modules\@ngtools\webpack\src\plugin.js:448:24)
    at process._tickCallback (internal/process/next_tick.js:109:7)

webpack: Failed to compile.
```
any guess what happended?

**Comment by susonwaiba** [comment]
OK. I got it. [https://github.com/Alberthaff/ngx-papaparse/tree/v1](https://github.com/Alberthaff/ngx-papaparse/tree/v1) for v4 and v2
